---
title: "Merging COVER data quarters together to analyse rotavirus vaccination uptake by GP practice"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Merging quarters BY GP PRACTICE

Install and load packages
```{r}
options(repos = "https://cloud.r-project.org")
library(readxl)
library(data.table)
#library("xlsx")
library("readODS")
library(dplyr)

```

```{r}
# Data course with each quarter available at time of analysis saved with nomenclature "[quarter number] coverGP [mon/yr mon/yr].ods" 
# Example "1 coverGP Apr19Jun19.ods"

# NOTE: The code was changed from rota to MMR vaccine so wherever 'rota' is references, it should mean MMR
```

```{r Run for all dates, echo=FALSE} 

data_all = NULL
for (j in 1:22){
  if (j==1){
    data <- read_ods("./COVER datasets April 2019 - March 2023/1 coverGP Apr19Jun19.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(7012:7014)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
  } else if (j==2){
    data <- read_ods("./COVER datasets April 2019 - March 2023/2 coverGP Jul19Sep19.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6973:6976)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
  } else if (j==3){
    data <- read_ods("./COVER datasets April 2019 - March 2023/3 coverGP Oct19Dec19.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6915:6917)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
  } else if (j==4){
    data <- read_ods("./COVER datasets April 2019 - March 2023/4 coverGP Jan20Mar20.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6905:6907)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
  } else if (j==5){
    data <- read_ods("./COVER datasets April 2019 - March 2023/5 coverGP Apr20Jun20.ods" , sheet = 2 , skip = 6)
    rows_to_remove <- c(6768,6769)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,11,13, 17,21,22)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
  } else if (j==6){
    data <- read_ods("./COVER datasets April 2019 - March 2023/6 coverGP Jul20Sep20.ods" , sheet = 2 , skip = 6)
    rows_to_remove <- c(6737)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,11,13, 17,21,22)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
  } else if (j==7){
    data <- read_ods("./COVER datasets April 2019 - March 2023/7 coverGP Oct20Dec20.ods" , sheet = 2 , skip = 4)
    rows_to_remove <- c(6719, 6720)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,11,13, 17,21,22)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
  } else if (j==8){
    data <- read_ods("./COVER datasets April 2019 - March 2023/8 coverGP Jan21Mar21.ods" , sheet = 2 , skip = 4)
    rows_to_remove <- c(6691, 6692)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
  } else if (j==9){
    data <- read_ods("./COVER datasets April 2019 - March 2023/9 coverGP Apr21Jun21.ods" , sheet = 2 , skip = 4)
    rows_to_remove <- c(6605, 6606)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
  } else if (j==10){
    data <- read_ods("./COVER datasets April 2019 - March 2023/10 coverGP Jul21Sep21.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6509)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
  } else if (j==11){
    data <- read_ods("./COVER datasets April 2019 - March 2023/11 coverGP Oct21Dec21.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6513)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
  } else if (j==12){
    data <- read_ods("./COVER datasets April 2019 - March 2023/12 coverGP Jan22Mar22.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6482)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
  } else if (j==13){
    data <- read_ods("./COVER datasets April 2019 - March 2023/13 coverGP Apr22Jun22.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6477)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
  } else if (j==14){
    data <- read_ods("./COVER datasets April 2019 - March 2023/14 coverGP Jul22Sep22.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6448)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,9,11, 15,19,20)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
  } else if (j==15){
    data <- read_ods("./COVER datasets April 2019 - March 2023/15 coverGP Oct22Dec22.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6429)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
  } else if (j==16){
    data <- read_ods("./COVER datasets April 2019 - March 2023/16 coverGP Jan23Mar23.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6398)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
    names(data)[3] <- "24m Denominator"
    names(data)[4] <- "24m MMR1%"
    names(data)[5] <- "5y Denominator"
    names(data)[6] <- "5y MMR1%"
    names(data)[7] <- "5y MMR2%"
  } else if (j==17){
    data <- read_ods("./COVER datasets April 2019 - March 2023/17 coverGP Apr23Jun23.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6372)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
    names(data)[3] <- "24m Denominator"
    names(data)[4] <- "24m MMR1%"
    names(data)[5] <- "5y Denominator"
    names(data)[6] <- "5y MMR1%"
    names(data)[7] <- "5y MMR2%"
  } else if (j==18){
    data <- read_ods("./COVER datasets April 2019 - March 2023/18 coverGP Jul23Sep23.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6342)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
    names(data)[3] <- "24m Denominator"
    names(data)[4] <- "24m MMR1%"
    names(data)[5] <- "5y Denominator"
    names(data)[6] <- "5y MMR1%"
    names(data)[7] <- "5y MMR2%"
  } else if (j==19){
    data <- read_ods("./COVER datasets April 2019 - March 2023/19 coverGP Oct23Dec23.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6307)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
    names(data)[3] <- "24m Denominator"
    names(data)[4] <- "24m MMR1%"
    names(data)[5] <- "5y Denominator"
    names(data)[6] <- "5y MMR1%"
    names(data)[7] <- "5y MMR2%"
  } else if (j==20){
    data <- read_ods("./COVER datasets April 2019 - March 2023/20 coverGP Jan24Mar24.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6292)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
    names(data)[3] <- "24m Denominator"
    names(data)[4] <- "24m MMR1%"
  } else if (j==21){
    data <- read_ods("./COVER datasets April 2019 - March 2023/21 coverGP Apr24Jun24.ods" , sheet = 2 , skip = 2)
    rows_to_remove <- c(6266)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
    names(data)[3] <- "24m Denominator"
    names(data)[4] <- "24m MMR1%"
    names(data)[5] <- "5y Denominator"
    names(data)[6] <- "5y MMR1%"
    names(data)[7] <- "5y MMR2%"
  } else if (j==22){
    data <- read_ods("./COVER datasets April 2019 - March 2023/22 coverGP Jul24Sept24.ods" , sheet = 2 , skip = 4)
    rows_to_remove <- c(6239)
    data <- data[-rows_to_remove, ]
    #Keep only rota column and GP codes (omit CCG info and other vaccs here)
    data <- data[,c(3,4,10,12, 16,20,21)]
    #Rename CCG and practice columns to match others
    names(data)[1] <- "ODS Upper Tier LA Code"
    names(data)[2] <- "Practice code"
    names(data)[3] <- "24m Denominator"
    names(data)[4] <- "24m MMR1%"
    names(data)[5] <- "5y Denominator"
    names(data)[6] <- "5y MMR1%"
    names(data)[7] <- "5y MMR2%"
  }
  
  
  
  
  
  #Check classes, switch ODS and Practice codes to characters
  data$`ODS Upper Tier LA Code`<- as.character(data$`ODS Upper Tier LA Code`)
  data$`Practice code` <- as.character(data$`Practice code`)
  data$`24m MMR1%` <- as.numeric(data$`24m MMR1%`)
  data$`5y MMR1%` <- as.numeric(data$`5y MMR1%`)
  data$`5y MMR2%` <- as.numeric(data$`5y MMR2%`)
  
  #Find out how many unknown codes
  count_V81999_unknown_GPcodes <- table(data$`Practice code`)["V81999"]
  #Remove unknown codes
  data <- data[!data$`Practice code` == "V81999", ]
  
  #Find out denoms less than 5 people and work out maximum that would be lost
  count_less_than_5_denoms <- table(data$`24m Denominator`)["*"]
  print(count_less_than_5_denoms)
  maximum_children_lost_low_denoms <- count_less_than_5_denoms*5
  print(maximum_children_lost_low_denoms)
  data$`24m Denominator` <- as.numeric(data$`24m Denominator`)
  total_denom <- sum(data$`24m Denominator`, na.rm=TRUE)
  maximum_lost_percentage <- ((maximum_children_lost_low_denoms / total_denom) * 100)
  print(maximum_lost_percentage)
  
  
  #Rename to columns to dated quarters and to dated df and add date column
  names(data)[2] <- "Practice_code"
  names(data)[3] <- "24m Denom"
  names(data)[4] <- "MMR1% 24m"
  names(data)[5] <- "5y Denom"
  names(data)[6] <- "MMR1% 5y"
  names(data)[7] <- "MMR2% 5y"
  data$Quarter_number <- j
  data_all <- bind_rows(data_all, as.data.table(data))
  
}
write.csv(data_all, "GP MMR merge length ways.csv")
print(data_all)


```


